import Nav from "../components/Nav/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body>
      <Nav />
      {children}
    </body>
  );
}
