import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import Nav from "./components/Nav/Nav";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={GeistSans.className} lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
