import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { AuthContextProvider } from "./contexts/AuthContext";

export const metadata = {
  title: "TradeTide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={GeistSans.className} lang="en">
      <AuthContextProvider>
        <body>{children}</body>
      </AuthContextProvider>
    </html>
  );
}
